"""initial schema

Revision ID: 48522eefca9f
Revises: 
Create Date: 2026-07-18 18:51:36.226322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48522eefca9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_color', sa.String(length=16), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('who_i_am', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('bigrams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('prev_label', sa.String(length=100), nullable=False),
    sa.Column('next_label', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'prev_label', 'next_label')
    )
    op.create_index(op.f('ix_bigrams_profile_id'), 'bigrams', ['profile_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('grid_columns', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_profile_id'), 'boards', ['profile_id'], unique=False)
    op.create_table('coach_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strength', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'week')
    )
    op.create_index(op.f('ix_coach_cards_profile_id'), 'coach_cards', ['profile_id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('board_id', sa.String(length=32), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_profile_id'), 'communication_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_timestamp'), 'communication_logs', ['timestamp'], unique=False)
    op.create_table('gap_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('board_id', sa.String(length=32), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'board_id', 'week_of')
    )
    op.create_index(op.f('ix_gap_alerts_profile_id'), 'gap_alerts', ['profile_id'], unique=False)
    op.create_table('gap_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('board_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_signals_profile_id'), 'gap_signals', ['profile_id'], unique=False)
    op.create_index(op.f('ix_gap_signals_timestamp'), 'gap_signals', ['timestamp'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('mood_symbol', sa.JSON(), nullable=True),
    sa.Column('sentences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_profile_id'), 'journal_entries', ['profile_id'], unique=False)
    op.create_table('tap_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('board_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tap_logs_profile_id'), 'tap_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_tap_logs_timestamp'), 'tap_logs', ['timestamp'], unique=False)
    op.create_table('board_symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('word_type', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_symbols_board_id'), 'board_symbols', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_symbols_board_id'), table_name='board_symbols')
    op.drop_table('board_symbols')
    op.drop_index(op.f('ix_tap_logs_timestamp'), table_name='tap_logs')
    op.drop_index(op.f('ix_tap_logs_profile_id'), table_name='tap_logs')
    op.drop_table('tap_logs')
    op.drop_index(op.f('ix_journal_entries_profile_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_gap_signals_timestamp'), table_name='gap_signals')
    op.drop_index(op.f('ix_gap_signals_profile_id'), table_name='gap_signals')
    op.drop_table('gap_signals')
    op.drop_index(op.f('ix_gap_alerts_profile_id'), table_name='gap_alerts')
    op.drop_table('gap_alerts')
    op.drop_index(op.f('ix_communication_logs_timestamp'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_profile_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_coach_cards_profile_id'), table_name='coach_cards')
    op.drop_table('coach_cards')
    op.drop_index(op.f('ix_boards_profile_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_bigrams_profile_id'), table_name='bigrams')
    op.drop_table('bigrams')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
