"""add kid login credentials

Revision ID: 8f8ca7b5caae
Revises: 8da214c6ec14
Create Date: 2026-07-29 19:15:42.022041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8ca7b5caae'
down_revision: Union[str, Sequence[str], None] = '8da214c6ec14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('failed_pin_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('profiles', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_column('profiles', 'locked_until')
    op.drop_column('profiles', 'failed_pin_attempts')
    op.drop_column('profiles', 'pin_hash')
    op.drop_column('profiles', 'username')
    # ### end Alembic commands ###
