"""add name to users

Revision ID: b1c8f60c23db
Revises: 48522eefca9f
Create Date: 2026-07-18 23:12:23.586944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c8f60c23db'
down_revision: Union[str, Sequence[str], None] = '48522eefca9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows so the NOT NULL add is safe;
    # new inserts always supply a real value via the ORM/API.
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False, server_default=''))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
